CREATE TABLE sizeOnz(
    id SERIAL PRIMARY KEY,
    menu_id INT NOT NULL REFERENCES menuItems(id) ON DELETE CASCADE,
    size INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);